// This file was automatically generated by the NPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `ApplicationDatabase`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      ``
//     Schema:                 ``
//     Include Views:          `False`


// -----------------------------------------------------------------------------------------
// Failed to read database schema - The ConnectionString property has not been initialized.
// -----------------------------------------------------------------------------------------


