<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Strongly typed fluent SQL builder for NPoco.</Description>
    <TargetFrameworks>net462;netstandard2.0;netstandard2.1;net8.0;net10.0</TargetFrameworks>
    <AssemblyName>NPoco.FluentSql</AssemblyName>
    <PackageId>NPoco.FluentSql</PackageId>
    <VersionPrefix>0.2.0</VersionPrefix>
    <Authors>Adam Schröder</Authors>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NPoco\NPoco.csproj" />
  </ItemGroup>
</Project>
